### ISSUE TITLE
Issues installing `png `Reason: tried: '/opt/homebrew/Cellar/r/4.2.0/lib/R/lib/libz.1.dylib' (no such file)`

### ISSUE THREAD

**Issue by dereckdemezquita** [s-u/png#6] opened 2022-06-15 03:37 UTC
I had great troubles trying to install this. I use it as it is a dependency for `ComplexHeatmap`. I was able to get it installed and seems everything is working. However, I post this here as I want to document this solution for others - and maybe confirm my solution by more expert peoples.

## The error

I was getting this error specifically:

```r
install.packages("png")
```

```
trying URL 'https://cran.microsoft.com/src/contrib/png_0.1-7.tar.gz'
Content type 'application/octet-stream' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/opt/homebrew/Cellar/r/4.2.0/lib/R/include" -DNDEBUG   -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include -I/opt/homebrew/include   `libpng-config --cflags` -fPIC  -Wno-implicit-function-declaration  -c read.c -o read.o
clang -I"/opt/homebrew/Cellar/r/4.2.0/lib/R/include" -DNDEBUG   -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include -I/opt/homebrew/include   `libpng-config --cflags` -fPIC  -Wno-implicit-function-declaration  -c write.c -o write.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.2.0/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/xz/lib -L/opt/homebrew/lib -o png.so read.o write.o -L/Users/neurox1/Tools/miniconda3/lib -lpng16 -lz -L/opt/homebrew/Cellar/r/4.2.0/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /opt/homebrew/lib/R/site-library/00LOCK-png/00new/png/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘png’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/homebrew/lib/R/site-library/00LOCK-png/00new/png/libs/png.so':
  dlopen(/opt/homebrew/lib/R/site-library/00LOCK-png/00new/png/libs/png.so, 0x0006): Library not loaded: @rpath/libz.1.dylib
  Referenced from: /opt/homebrew/lib/R/site-library/00LOCK-png/00new/png/libs/png.so
  Reason: tried: '/opt/homebrew/Cellar/r/4.2.0/lib/R/lib/libz.1.dylib' (no such file)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/homebrew/lib/R/site-library/png’

The downloaded source packages are in
	‘/private/tmp/Rtmp6qcnWH/downloaded_packages’
Warning message:
In install.packages("png") :
  installation of package ‘png’ had non-zero exit status
```

## `sessionInfo()`

Here is my `sessionInfo()`; indeed I'm running an `M1`, I was running and installed `png` previously no issues on version `4.1.3` of `R`, but recently I updated to `4.2.0` and had this issue.

```r
sessionInfo()
```

```
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin21.3.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
BLAS:   /opt/homebrew/Cellar/openblas/0.3.20/lib/libopenblasp-r0.3.20.dylib
LAPACK: /opt/homebrew/Cellar/r/4.2.0/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0    data.table_1.14.2
```

## My solution; `symlink` `ibz.1.dylib` to where `R` is looking for it

I noticed this in the error: `Reason: tried: '/opt/homebrew/Cellar/r/4.2.0/lib/R/lib/libz.1.dylib' (no such file)`

I installed this library with `brew`:

```bash
brew info zlib
```

```
zlib: stable 1.2.12 (bottled), HEAD [keg-only]
General-purpose lossless data-compression library
https://zlib.net/
/opt/homebrew/Cellar/zlib/1.2.12 (12 files, 397.6KB)
  Poured from bottle on 2022-06-14 at 18:43:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/zlib.rb
License: Zlib
==> Options
--HEAD
	Install HEAD version
==> Caveats
zlib is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"

For pkg-config to find zlib you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

==> Analytics
install: 52,294 (30 days), 145,163 (90 days), 422,076 (365 days)
install-on-request: 49,866 (30 days), 138,448 (90 days), 409,357 (365 days)
build-error: 1 (30 days)
```

So naturally I did this:

```bash
ln -s /opt/homebrew/opt/zlib/lib/libz.1.dylib /opt/homebrew/Cellar/r/4.2.0/lib/R/lib/
```

Finally I tried installing again after re-loading `R` with `sudo` and got this:

```
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin21.3.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
BLAS:   /opt/homebrew/Cellar/openblas/0.3.20/lib/libopenblasp-r0.3.20.dylib
LAPACK: /opt/homebrew/Cellar/r/4.2.0/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0    data.table_1.14.2
```

```r
> install.packages("png")
Installing package into ‘/opt/homebrew/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.microsoft.com/src/contrib/png_0.1-7.tar.gz'
Content type 'application/octet-stream' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/opt/homebrew/Cellar/r/4.2.0/lib/R/include" -DNDEBUG   -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include -I/opt/homebrew/include   `libpng-config --cflags` -fPIC  -mtune=native -g -O2 -Wall -pedantic -Wconversion -L/opt/local/lib -c read.c -o read.o
clang-13: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]
read.c:29:21: warning: implicit conversion changes signedness: 'int' to 'png_size_t'
      (aka 'unsigned long') [-Wsign-conversion]
        to_read = (rj->len - rj->ptr);
                ~  ~~~~~~~~^~~~~~~~~
read.c:244:25: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
            int pln = rowbytes / width;
                ~~~   ~~~~~~~~~^~~~~~~
read.c:244:16: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
            int pln = rowbytes / width;
                      ^~~~~~~~ ~
read.c:260:4: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
                        RX_swap32(*idata);
                        ^~~~~~~~~~~~~~~~~
read.c:48:120: note: expanded from macro 'RX_swap32'
  ...= (((unsigned int)X) >> 24) | ((((unsigned int)X) >> 8) & 0xff00) | (((unsigned int)X) << 24) | ((((unsigned int)X) & 0xff00) << 8)
     ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
read.c:266:17: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
                        *(idata++) = R_RGB((unsigned int) row_pointers[y][x],
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/r/4.2.0/lib/R/include/R_ext/GraphicsDevice.h:862:45: note: expanded from macro
      'R_RGB'
#define R_RGB(r,g,b)    ((r)|((g)<<8)|((b)<<16)|0xFF000000)
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
read.c:273:17: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
                        *(idata++) = R_RGBA((unsigned int) row_pointers[y][x],
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/r/4.2.0/lib/R/include/R_ext/GraphicsDevice.h:863:48: note: expanded from macro
      'R_RGBA'
#define R_RGBA(r,g,b,a) ((r)|((g)<<8)|((b)<<16)|((a)<<24))
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
read.c:281:17: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
                        *(idata++) = R_RGB((unsigned int) row_pointers[y][x],
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/r/4.2.0/lib/R/include/R_ext/GraphicsDevice.h:862:45: note: expanded from macro
      'R_RGB'
#define R_RGB(r,g,b)    ((r)|((g)<<8)|((b)<<16)|0xFF000000)
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
read.c:286:24: warning: implicit conversion changes signedness: 'png_uint_32' (aka 'unsigned int')
      to 'int' [-Wsign-conversion]
            INTEGER(dim)[0] = height;
                            ~ ^~~~~~
read.c:287:24: warning: implicit conversion changes signedness: 'png_uint_32' (aka 'unsigned int')
      to 'int' [-Wsign-conversion]
            INTEGER(dim)[1] = width;
                            ~ ^~~~~
read.c:293:34: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
            int x, y, p, pln = rowbytes / width, pls = width * height;
                         ~~~   ~~~~~~~~~^~~~~~~
read.c:293:25: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
            int x, y, p, pln = rowbytes / width, pls = width * height;
                               ^~~~~~~~ ~
read.c:293:55: warning: implicit conversion changes signedness: 'unsigned int' to 'int'
      [-Wsign-conversion]
            int x, y, p, pln = rowbytes / width, pls = width * height;
                                                 ~~~   ~~~~~~^~~~~~~~
read.c:296:39: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                res = PROTECT(allocVector(REALSXP, (rowbytes * height) / 2));
                                                    ^~~~~~~~ ~
/opt/homebrew/Cellar/r/4.2.0/lib/R/include/Rinternals.h:367:31: note: expanded from macro 'PROTECT'
#define PROTECT(s)      Rf_protect(s)
                                   ^
read.c:299:38: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                res = PROTECT(allocVector(REALSXP, rowbytes * height));
                                                   ^~~~~~~~ ~
/opt/homebrew/Cellar/r/4.2.0/lib/R/include/Rinternals.h:367:31: note: expanded from macro 'PROTECT'
#define PROTECT(s)      Rf_protect(s)
                                   ^
read.c:306:32: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)(
                                                ~ ~~^~~~~
read.c:306:17: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)(
                                     ^ ~
read.c:306:13: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)(
                                 ^ ~
read.c:314:32: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)row_pointers[y][x * pln + p]) / 255.0;
                                                ~ ~~^~~~~
read.c:314:17: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)row_pointers[y][x * pln + p]) / 255.0;
                                     ^ ~
read.c:314:13: warning: implicit conversion changes signedness: 'int' to 'unsigned int'
      [-Wsign-conversion]
                            data[y + x * height + p * pls] = ((double)row_pointers[y][x * pln + p]) / 255.0;
                                 ^ ~
read.c:316:24: warning: implicit conversion changes signedness: 'png_uint_32' (aka 'unsigned int')
      to 'int' [-Wsign-conversion]
            INTEGER(dim)[0] = height;
                            ~ ^~~~~~
read.c:317:24: warning: implicit conversion changes signedness: 'png_uint_32' (aka 'unsigned int')
      to 'int' [-Wsign-conversion]
            INTEGER(dim)[1] = width;
                            ~ ^~~~~
read.c:111:13: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long')
      to 'int' [-Wshorten-64-to-32]
        rowbytes = png_get_rowbytes(png_ptr, info_ptr);
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
read.c:216:13: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long')
      to 'int' [-Wshorten-64-to-32]
        rowbytes = png_get_rowbytes(png_ptr, info_ptr);
                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24 warnings generated.
clang -I"/opt/homebrew/Cellar/r/4.2.0/lib/R/include" -DNDEBUG   -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include -I/opt/homebrew/include   `libpng-config --cflags` -fPIC  -mtune=native -g -O2 -Wall -pedantic -Wconversion -L/opt/local/lib -c write.c -o write.o
clang-13: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]
write.c:35:26: warning: implicit conversion changes signedness: 'int' to 'png_size_t'
      (aka 'unsigned long') [-Wsign-conversion]
            to_write = (rj->len - rj->ptr);
                     ~  ~~~~~~~~^~~~~~~~~
write.c:184:44: warning: implicit conversion changes signedness: 'int' to 'png_uint_32'
      (aka 'unsigned int') [-Wsign-conversion]
    png_set_IHDR(png_ptr, info_ptr, width, height, 8,
    ~~~~~~~~~~~~                           ^~~~~~
write.c:184:37: warning: implicit conversion changes signedness: 'int' to 'png_uint_32'
      (aka 'unsigned int') [-Wsign-conversion]
    png_set_IHDR(png_ptr, info_ptr, width, height, 8,
    ~~~~~~~~~~~~                    ^~~~~
write.c:190:58: warning: implicit conversion turns floating-point number into integer: 'double' to
      'png_uint_32' (aka 'unsigned int') [-Wfloat-conversion]
        png_set_pHYs(png_ptr, info_ptr, dpi_x * 39.37008, dpi_y * 39.37008, PNG_RESOLUTION_METER);
        ~~~~~~~~~~~~                                      ~~~~~~^~~~~~~~~~
write.c:190:40: warning: implicit conversion turns floating-point number into integer: 'double' to
      'png_uint_32' (aka 'unsigned int') [-Wfloat-conversion]
        png_set_pHYs(png_ptr, info_ptr, dpi_x * 39.37008, dpi_y * 39.37008, PNG_RESOLUTION_METER);
        ~~~~~~~~~~~~                    ~~~~~~^~~~~~~~~~
write.c:192:57: warning: implicit conversion turns floating-point number into integer: 'double' to
      'png_uint_32' (aka 'unsigned int') [-Wfloat-conversion]
        png_set_pHYs(png_ptr, info_ptr, dpi_x * 10000.0, dpi_y * 10000.0, PNG_RESOLUTION_UNKNOWN);
        ~~~~~~~~~~~~                                     ~~~~~~^~~~~~~~~
write.c:192:40: warning: implicit conversion turns floating-point number into integer: 'double' to
      'png_uint_32' (aka 'unsigned int') [-Wfloat-conversion]
        png_set_pHYs(png_ptr, info_ptr, dpi_x * 10000.0, dpi_y * 10000.0, PNG_RESOLUTION_UNKNOWN);
        ~~~~~~~~~~~~                    ~~~~~~^~~~~~~~~
write.c:216:38: warning: implicit conversion changes signedness: 'int' to 'size_t'
      (aka 'unsigned long') [-Wsign-conversion]
        row_pointers = (png_bytepp) R_alloc(height, sizeof(png_bytep));
                                    ~~~~~~~ ^~~~~~
write.c:217:34: warning: implicit conversion changes signedness: 'int' to 'size_t'
      (aka 'unsigned long') [-Wsign-conversion]
        flat_rows = (png_bytep) R_alloc(height, width * planes);
                                ~~~~~~~ ^~~~~~
write.c:236:38: warning: implicit conversion changes signedness: 'int' to 'unsigned long'
      [-Wsign-conversion]
                    memcpy(row_pointers[y], idata, width * sizeof(int));
                                                   ^~~~~ ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/secure/_string.h:63:33: note: 
      expanded from macro 'memcpy'
                __builtin___memcpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^~~~~~~~~~~
10 warnings generated.
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.2.0/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/xz/lib -L/opt/homebrew/lib -o png.so read.o write.o -L/Users/neurox1/Tools/miniconda3/lib -lpng16 -lz -L/opt/homebrew/Cellar/r/4.2.0/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /opt/homebrew/lib/R/site-library/00LOCK-png/00new/png/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (png)

The downloaded source packages are in
	‘/private/tmp/Rtmp6qcnWH/downloaded_packages’
> library("png")
```

Everything seems to be working now after some testing, however I am wary of the compilation errors and am seeking more expert opinion please.

**Comment by s-u** [comment] 2022-11-29 09:30
Closing since binary is available from CRAN and all above issues are caused by Homebrew - as it warns you'd have to setup the environment for it to work first.

**Closed by s-u** 2022-11-29 09:30 UTC
